name: Build images

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/build-images.yml
      - images/**

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image: [{ name: dioxus-cli, version: 0.5.4 }]
        platform: [linux/amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3    
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: images/${{ matrix.image.name }}.dockerfile
          build-args: |
            TOOL_VERSION=${{ matrix.image.version }}
          tags: |
            ghcr.io/oxidrive/ci/${{ matrix.image.name }}:${{ matrix.image.version }}
